#!/bin/sh
## compile ##
clear                                                       \
 && gcc -ansi -I./src -c ./src/fileIO.c -o ./bin/fileIO.o   \
 && gcc -ansi -I./src -c ./src/simQ.c   -o ./bin/simQ.o     \
 && gcc bin/fileIO.o bin/simQ.o         -o bin/simQ         \
 && echo "Complete"
